#!/bin/bash
# Autogenerated by Terminus
#####
## Build Environment Setup
#####

# Example:
# setup_service java 1.8.342
# setup_service maven 3.5.4
# cd "${OKTA_HOME}/${REPO}" && mvn clean install -DskipTests -DskipSeleniumTests -Dpmd.skip=true -Dcheckstyle.skip -Dspotbugs.skip=true -Ddockerfile.skip=true

#####
## Execute Dependency Scanning
#####

dependency_scan
