name: 'Feature request'
description: 'File a feature request'

labels:
  - 'enhancement'

body:
  - type: 'markdown'
    attributes:
      value: |-
        Thank you for requesting a feature. Please complete the form below so we can triage and prioritize your feature.

  - id: 'new_issue'
    type: 'checkboxes'
    attributes:
      label: 'New issue?'
      options:
        - label: 'I have reviewed the [Existing Issues](https://github.com/atko-eng/okta-mcp-server/issues) and confirm this is not an existing issue.'
          required: true

  - id: 'tldr'
    type: 'textarea'
    attributes:
      label: 'Feature'
      description: 'Describe the feature in 1-2 sentences.'
    validations:
      required: true

  - id: 'additional'
    type: 'textarea'
    attributes:
      label: 'Additional information'
      description: 'Is there anything else you think we should know?'